/**
 * ISO 4217 active currencies.
 *
 * The naira first and a short list of majors pinned to the top, because a
 * Nigerian policy tool should not make its most likely audience scroll to N.
 * Symbols are used where a currency genuinely has one; elsewhere the code is
 * the symbol, which is what banks do too.
 */

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export const PINNED = ["NGN", "USD", "EUR", "GBP", "CNY", "ZAR"];

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "United States Dollar", symbol: "$" },
  { code: "NGN", name: "Nigerian Naira", symbol: "\u20a6" },
  { code: "EUR", name: "Euro", symbol: "\u20ac" },
  { code: "GBP", name: "Pound Sterling", symbol: "\u00a3" },
  { code: "AED", name: "UAE Dirham", symbol: "\u062f.\u0625" },
  { code: "AFN", name: "Afghan Afghani", symbol: "\u060b" },
  { code: "ALL", name: "Albanian Lek", symbol: "L" },
  { code: "AMD", name: "Armenian Dram", symbol: "\u058f" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "\u0192" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "AWG", name: "Aruban Florin", symbol: "\u0192" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "\u20bc" },
  { code: "BAM", name: "Bosnia Convertible Mark", symbol: "KM" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "\u09f3" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "\u043b\u0432" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".\u062f.\u0628" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CLP", name: "Chilean Peso", symbol: "CLP$" },
  { code: "CNY", name: "Chinese Yuan", symbol: "\u00a5" },
  { code: "COP", name: "Colombian Peso", symbol: "COL$" },
  { code: "CRC", name: "Costa Rican Col\u00f3n", symbol: "\u20a1" },
  { code: "CUP", name: "Cuban Peso", symbol: "$MN" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc" },
  { code: "CZK", name: "Czech Koruna", symbol: "K\u010d" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "DZD", name: "Algerian Dinar", symbol: "\u062f.\u062c" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E\u00a3" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$" },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "\u00a3" },
  { code: "GEL", name: "Georgian Lari", symbol: "\u20be" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH\u20b5" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "\u00a3" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "\u20aa" },
  { code: "INR", name: "Indian Rupee", symbol: "\u20b9" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "\u0639.\u062f" },
  { code: "IRR", name: "Iranian Rial", symbol: "\ufdfc" },
  { code: "ISK", name: "Icelandic Kr\u00f3na", symbol: "kr" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "\u062f.\u0627" },
  { code: "JPY", name: "Japanese Yen", symbol: "\u00a5" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "\u043b\u0432" },
  { code: "KHR", name: "Cambodian Riel", symbol: "\u17db" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { code: "KPW", name: "North Korean Won", symbol: "\u20a9" },
  { code: "KRW", name: "South Korean Won", symbol: "\u20a9" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "\u062f.\u0643" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "\u20b8" },
  { code: "LAK", name: "Lao Kip", symbol: "\u20ad" },
  { code: "LBP", name: "Lebanese Pound", symbol: "\u0644.\u0644" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { code: "LYD", name: "Libyan Dinar", symbol: "\u0644.\u062f" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "\u062f.\u0645" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "MKD", name: "Macedonian Denar", symbol: "\u0434\u0435\u043d" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "MNT", name: "Mongolian T\u00f6gr\u00f6g", symbol: "\u20ae" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "\u20a8" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
  { code: "NIO", name: "Nicaraguan C\u00f3rdoba", symbol: "C$" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "\u0930\u0942" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "OMR", name: "Omani Rial", symbol: "\u0631.\u0639" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
  { code: "PHP", name: "Philippine Peso", symbol: "\u20b1" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs" },
  { code: "PLN", name: "Polish Z\u0142oty", symbol: "z\u0142" },
  { code: "PYG", name: "Paraguayan Guaran\u00ed", symbol: "\u20b2" },
  { code: "QAR", name: "Qatari Riyal", symbol: "\u0631.\u0642" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "RSD", name: "Serbian Dinar", symbol: "\u0434\u0438\u043d" },
  { code: "RUB", name: "Russian Ruble", symbol: "\u20bd" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "SAR", name: "Saudi Riyal", symbol: "\u0631.\u0633" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "\u20a8" },
  { code: "SDG", name: "Sudanese Pound", symbol: "\u062c.\u0633" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "SHP", name: "Saint Helena Pound", symbol: "\u00a3" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh.So." },
  { code: "SRD", name: "Surinamese Dollar", symbol: "Sr$" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS\u00a3" },
  { code: "STN", name: "S\u00e3o Tom\u00e9 Dobra", symbol: "Db" },
  { code: "SYP", name: "Syrian Pound", symbol: "\u00a3S" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E" },
  { code: "THB", name: "Thai Baht", symbol: "\u0e3f" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m" },
  { code: "TND", name: "Tunisian Dinar", symbol: "\u062f.\u062a" },
  { code: "TOP", name: "Tongan Pa\u02bbanga", symbol: "T$" },
  { code: "TRY", name: "Turkish Lira", symbol: "\u20ba" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "\u20b4" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
  { code: "UZS", name: "Uzbekistani So\u02bbm", symbol: "so\u02bbm" },
  { code: "VES", name: "Venezuelan Bol\u00edvar", symbol: "Bs." },
  { code: "VND", name: "Vietnamese \u0110\u1ed3ng", symbol: "\u20ab" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT" },
  { code: "WST", name: "Samoan T\u0101l\u0101", symbol: "WS$" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XPF", name: "CFP Franc", symbol: "\u20a3" },
  { code: "YER", name: "Yemeni Rial", symbol: "\ufdfc" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWG", name: "Zimbabwe Gold", symbol: "ZiG" },
];

export const byCode = (code: string) =>
  CURRENCIES.find((c) => c.code === code) ?? CURRENCIES[0];